################################################################################
# Copyright (c) 2017-2018, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

all:
	gcc -ggdb -c -o dsexample_lib.o -fPIC dsexample_lib.c
	ar rcs libdsexample.a dsexample_lib.o
